### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by nedjwab** [nedjwab/Recipe-app#8]
### In This issue @huseyinbiyik  and I set up our project's kanban board :
- [This is the link to the board ](https://github.com/nedjwab/Recipe-app/projects/1).
- we are a group of 2.
- Team member 1: @nedjwab.
- Team member 2  : @huseyinbiyik

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @nedjwab and @ibr5500,

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ibr5500** [comment]
Thank you @TedLivist for the review.
